import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const liveSite = process.env.NEXT_PUBLIC_BASE_URL;

export const metadata: Metadata = {
  title: "SEEES WEEK HIGHLIGHTS",
  description: "Generated by create next app",
  openGraph: {
    title:
      "SEEES WEEK HIGHLIGHTS",
    description:"The SEEES Week community came together for an unforgettable celebration filled with engaging workshops, inspiring talks, and memorable moments.",
    images: [
      {
        url: `${liveSite}/og.png?v=${Date.now()}`,
        width: 1200,
        height: 600,
        alt: "Lumen title image",
      },
    ],
  },
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link
          rel="icon"
          type="image/jpeg"
          // sizes="192x192"
          href="/logo.jpeg"
        />
      </head>
      <body className={`${inter.className} dark`}>
        {modal}
        {children}
      </body>
    </html>
  );
}
